apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedemo-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kubedemo
  template:
    metadata:
      labels:
        app: kubedemo
    spec:
      containers:
        - name: kubedemo
          image: sowmya959/sample:kubeimage
          ports:
            - containerPort: 5000
    
